### ISSUE TITLE
Conformance Profile Mandatory Content

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#1]
Currently there is no indication of which fields are mandatory and what format data those fields should contain.

Specification Page: https://nhsconnect.github.io/gpconnect/foundations_use_case_get_the_fhir_conformance_profile.html#api-usage

Currently we have test scenario's to test the following:

* The "format" element which defines what content types are accepted by the solution should have the value "application/xml+fhir" or "application/json+fhir". We do accept "xml" or "json" as this is standard for the FHIR specification.
* The "software" element must be present and contain the "name" and "version" sub elements.
* The "fhirVersion" element should be present and contain the value of the fhir version the endpoint supports, in this case it should be "1.0.2"

09/12/2016 - Added
* On the conformance profile example the Operation "name" element should be the "Name by which the operation/query is invoked". In the example conformance profile this should be changed to "gpc.getcarerecord" and it should be stated that this is mandatory as per the FHIR specification. https://www.hl7.org/fhir/conformance.html

All other mandatory or optional fields and formats should be specified on the GP Connect site.

**Comment by michaelmeasures** [comment]
@james-answer do you have a reference for the first point on using plain xml and json content types. I know this was supported in DSTU1 but I believe it was deprecated in DSTU2.

**Comment by james-answer** [comment]
It is still refered to in the resource detailed description section:

https://www.hl7.org/fhir/conformance-definitions.html#Conformance.format

It may be that everywhere else it has been depricated but they have just not updated this to match the changes.

**Comment by michaelmeasures** [comment]
@james-answer at the moment I think the SSP may be more strict and only allow the FHIR XML and FHIR JSON mime types (as that's what I understood at the time was specified to be declared in the Conformance Profile). Having looked back over the FHIR specification it does seem that they're more permissive. I think I'll likely have to raise a request under NWR-201 to have the other mime types added.

**Comment by michaelmeasures** [comment]
Closing out this issue as specification changes are to be handled under the main 'gpconnect' issues section.
