### ISSUE TITLE
Test suite pre-requisite file analysis (patient)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#100]
The “Test Suite Prerequisites.xls” says that for patient 14, “Patient not on spine but in provider system (i.e. no PDS)”.

However due to the way the test suite picks patients when executing tests sometimes this patient can be selected which can then potentially produces erroneous results. Analysis needed as to whether certain patients can be isolated i.e. not randomly called

**Comment by rbutterf** [comment]
patient14 has been removed from the random patients list
