### ISSUE TITLE
Appointments test suite - conflict between ORG Code in ODS code file and JWT requesting organisation

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#104]
For some amend and cancel tests the Organization Code 'ORG1' is called which references the ODSCodeMap.csv file. When executed these tests fail with the message 'ODS code [******] in JWT header doesn&amp;apos;t match code in request headers [******].

An example of one of these tests is:
'I perform a successful cancel appointment'

Raised to change these tests to bypass the Org Code and use the Requesting Org Code in the JWT

**Comment by rbutterf** [comment]
Wrong Org code used in ODS Codemap.csv file.. Once corrected tests work correctly
