### ISSUE TITLE
Foundations -Test suite change request -Find Patient -Deceased

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-provider-testing#106]
Amend test suite to check the response for Find Patient requests containing details of a patient whose record is marked as Deceased. CONS-FoundationAPITest5

**Comment by rbutterf** [comment]
Test suite already contains Scenario: Patient search response does not return deceased patient

**Comment by rbutterf** [comment]
Test suit already contains Scenario: Patient search response does not return deceased patient
