### ISSUE TITLE
Foundations -Test suite change request -Register Patient - PDS mismatch

### ISSUE THREAD

**Issue by privchiadzwa** [nhsconnect/gpconnect-provider-testing#111]
Amend   test suite to check the response for Register Patient requests containing   details of a patient whose demographic details do not match PDS.   CONS-FoundationAPITest51
--

**Comment by rbutterf** [comment]
Added 
Scenario: Register patient with family name not matching PDS
Scenario: Register patient with gender not matching PDS
Scenario: Register patient with birth date not matching PDS

**Comment by rbutterf** [comment]
unable to test as demonstrator does not access PDS. manual tests needed
