### ISSUE TITLE
Knock on changes occurring after mods for Consumer Testing

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsconnect/gpconnect-provider-testing#115]
As per spec sensitive records are now no longer returned:
These are patients 9, 10 and 15

Remove patients 9 and 10 from the following tests:
Retrieve the allergy structured record section for a patient including resolved allergies
Retrieve the allergy structured record section for a patient excluding resolved allergies

Remove patients 9,10 and 15 from RandomPatientSteps.cs

For fix to failing "patient not on spine" test  currently the nhs number is hard coded as 9019546082 in file RegisterPatientSteps.cs .
It needs to be *derived* via a lookup for Patient14 from NHSNoMap.csv which currently has an nhs number of 9476718943

Append a new Patient to NHSNoMap.csv representing an inactive record
patient21,9658219748

**Comment by rbutterf** [comment]
removed patients 9,10 & 15 from tests
added lookup for patient14
added patient21 for inactive tests and NHSNomap.csv and Test Suite pre-requisites spreadsheets
