### ISSUE TITLE
Foundations and Appointments - Simplify Address data type population requirement (1.2.2) 

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#117]
•Remove requirement to populate Address.text in order to simplify address consumption.

•Add requirement to populate Address.use for patient addresses

•Update example payloads accordingly

See ticket https://github.com/nhsconnect/gpconnect/issues/567

**Comment by rbutterf** [comment]
address.text not validated by test suite
address.use validated by test suite

**Comment by AndrewGuiseley** [comment]
Amended manual test FAPM-51 - Text representation of the address to state that this should not be returned

**Comment by AndrewGuiseley** [comment]
Also amended the following manual tests:

FAPM-68- Patient contact text representation of the address to state that this should not be returned 
OSEM-11 - Address - General to remove reference to the population of the text element
LREM-17 - Address general to remove reference to the population of the text element
RAPM-50 - Text representation of the address to state that this should not be returned 
RAPM-67 - Patient contact text representation of the address to state that this should not be returned 
OSEM-9 - Address Use to state that the address use should be populated 
LREM-15 - Address use to state that the address use should be populated
FAPM-48 - Patient address use valueset to state that the address use shall be populated
FAPM-65 - Patient contact address use code valueset to state that the address use shall be populated 
RAPM-47 - Patient address use valueset to state that the address use shall be populated
RAPM-64 - Patient contact address use code valueset to state that the address use shall be populated
