### ISSUE TITLE
Foundations and Appointments - element population exclusions and general population guidance (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#120]
•Re-state and link to general FHIR resource population requirements on each Foundations and Appointment Management use case page

•Tidy up population requirements in each use case, applying consistency to those common elements explictly listed such as name, gender, birthDate, identifier, address and telecom

•Explicitly list Patient.nhsCommunication and Practitioner.nhsCommunication for population

•Add requirement to NOT populate the following elements:
•Patient.ethnicCategory
•Patient.religiousAffiliation
•Patient.patient-cadavericDonor
•Patient.residentialStatus
•Patient.treatmentCategory
•Patient.birthPlace
•Patient.maritalStatus
•Patient.multipleBirthBoolean
•Practitioner.telecom
•Practitioner.address
•Practitioner.birthDate
•Practitioner.photo
•Practitioner.qualification
•Schedule.specialty
•Slot.specialty
•Appointment.specialty
•Appointment.reason
•Organization.contact
•Organization.endpoint
•Location.endpoint

See tickets:
https://github.com/nhsconnect/gpconnect/issues/558
https://github.com/nhsconnect/gpconnect/issues/566
https://github.com/nhsconnect/gpconnect/issues/563

**Comment by rbutterf** [comment]
add tests to fail if elements are returned

**Comment by AndrewGuiseley** [comment]
Removed the following **manual** tests:

FAPM-14 - Ethnic Category extension - Find a Patient
RAPM-14 - Ethnic Category extension - Read a Patient
FAPM-15 - Religious Affiliation extension - Find a Patient
RAPM-15 - Religious Affiliation extension - Read a Patient
FAPM-16 - Patient cadaveric donor extension - Find a Patient
RAPM-16 - Patient cadaveric donor extension - Read a Patient
FAPM-17 - Residential status extension - Find a Patient
RAPM-17 - Residential status extension - Read a Patient
FAPM-18 - Treatment category extension - Find a Patient
RAPM-18 - Treatment category extension - Read a Patient
FAPM-25 - Patients registered Birth Place extension - Find a Patient
RAPM-26 - Patients registered Birth Place extension - Read a Patient
FAPM-53 - Patient marital status valueset - Find a Patient
RAPM-52 - Patient marital status valueset - Read a Patient
FAPM-54 - Multiple birth - Find a Patient - Find a Patient
RAPM-53 - Multiple birth - Read a Patient - Read a Patient
PSEM-15 - Telecom system valueset mapping - Find a Practitioner
PREM-15 - Telecom system valueset mapping - Read a Practitioner
PSEM-16 - Telecom use valueset mapping - Find a Practitioner
PREM-16 - Telecom use valueset mapping - Read a Practitioner
PSEM-17 - Telecom period multiple telecom contact points - Find a Practitioner
PREM-17 - Telecom period multiple telecom contact points - Read a Practitioner
PSEM-18 - Deletions to Telecom Contact Points - Find a Practitioner
PREM-18 - Deletions to Telecom Contact Points - Read a Practitioner
PSEM-19 - Telecom Rank element - Find a Practitioner
PREM-19 - Telecom Rank element - Read a Practitioner
PSEM-20 - Addess use code valueset - Find a Practitioner
PREM-20 - Addess use code valueset - Read a Practitioner
PSEM-21 - Address type valueset - Find a Practitioner
PREM-21 - Address type valueset - Read a Practitioner
PSEM-22 -  Address optional field mapping - Find a Practitioner
PREM-22 -  Address optional field mapping - Read a Practitioner
PSEM-23 - Address amendments - Find a Practitioner
PREM-23 - Address amendments - Read a Practitioner
PSEM-24 - Address multiples - Find a Practitioner
PREM-24 - Address multiples - Read a Practitioner
PSEM-26 - Birth date - Find a Practitioner
PREM-26 - Birth date - Read a Practitioner
PSEM-27 - Optional field mapping - Find a Practitioner
PSEM-28 - Multiple photos - Read a Practitioner
PREM-27 - Optional field mapping - Read a Practitioner
PREM-28 - Multiple photos - Read a Practitioner
PSEM-29 - Qualification use valueset - Find a Practitioner
PREM-29 - Qualification use valueset - Read a Practitioner
PSEM-30 - Qualification type user selected - Find a Practitioner
PREM-30 - Qualification type user selected - Read a Practitioner
PSEM-31 - Qualification identifier type valueset - Find a Practitioner
PREM-31 - Qualification identifier type valueset - Read a Practitioner
PSEM-32 - Qualification identification period - Find a Practitioner
PREM-32 - Qualification identification period - Read a Practitioner
PSEM-33 - Qualification assigner - Find a Practitioner
PREM-33 - Qualification assigner - Read a Practitioner
PSEM-34 - Qualification coded representation - Find a Practitioner
PREM-34 - Qualification coded representation - Read a Practitioner
PSEM-35 - Qualification code - user selected - Find a Practitioner
PREM-35 - Qualification code - user selected - Read a Practitioner
PSEM-36 - Qualification validity period - Find a Practitioner
PREM-36 - Qualification validity period - Read a Practitioner
PSEM-37 - Qualification issuer - Find a Practitioner
PREM-37 - Qualification issuer - Read a Practitioner
OSEM-14 - Organization Contact Purpose contact entity - Find an Organisation
OREM-15 - Organization Contact Purpose contact entity - Read an Organisation
OSEM-15 - Organization Contact Purpose - Coding - Find an Organisation
OREM -14 - Organization Contact Purpose - Coding - Read an Organisation
OSEM-16 - Organization Contact Name element population - Find an Organisation
OREM-16 - Organization Contact Name element population - Read an Organisation
OSEM-17 - Organization Contact Name - multiple contact names - Find an Organisation
OREM-17 - Organization Contact Name - multiple contact names - Read an Organisation
OSEM-18 - Organization Contact Name - updates and deletions - Find an Organisation
OREM-18 - Organization Contact Name - updates and deletions - Read an Organisation
OSEM-19 - Organization Contact Name use valueset - Find an Orgaisation
OREM-19 - Organization Contact Name use valueset - Read an Organisation
OSEM-20 - Telecom - Find an Organisation
OREM-20 - Telecom - Read an Organisation
OSEM-21 - Address Use - Find an Organisation
OREM-21 - Address Use - Read an Organisation
OSEM-22 - Address Type - Find an Organisation
OREM-22 - Address Type - Read an Organisation
OSEM-23 - Address - General - Find an Organisation
OREM-23 - Address - General - Read an Organisation
OSEM-24 - Address - Updates and deletions - Find an Organisation
OREM-24 - Address - Updates and deletions - Read an Organisation
OSEM-25 - Endpoint population - Find an Organisation
OREM-25 - Endpoint population - Read an Organisation
LREM-25 - Endpoint population - Read a Location
SFSM-4 - Practitioner Specialty of appointment schedule - Coding - Search for free slots
SFSM-5 - Practitioner Specialty - version of the coding system - Search for free slots
SFSM-6 - Practitioner Specialty - User selected - Search for free slots
SFSM-12 - Slot Specialty - Search for free slots - Search for free slots
BAAM-18 - Practitioner specialty of appointment - Book appointment
