### ISSUE TITLE
Foundations and Appointments - Populate Location.managingOrganization (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#121]
•Add explicit requirement to populate Location.managingOrganization in alignment with branch surgery model

•Also remove requirement to populate ODS ‘site’ code in Location.identifier

•Update example payloads accordingly.

See ticket - https://github.com/nhsconnect/gpconnect/issues/560

**Comment by AndrewGuiseley** [comment]
**Manual test scripts**

•Add explicit requirement to populate Location.managingOrganization in alignment with branch surgery model
Updated LREM-23 - Managing Organization - to state that this shall be populated and would typically be the GP Practice in a branch surgery model
•Also remove requirement to populate ODS ‘site’ code in Location.identifier
Updated LREM-1 - ODS Site Code to state that this information is not required as such and if provided then Consumers should ignore it

**Comment by rbutterf** [comment]
Added test to check Location.managingOrganization is populated and resolvable
