### ISSUE TITLE
Foundations - Populate Patient.managingOrganization (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#122]
Add explicit requirement to populate Patient.managingOrganization (Note: this is not necessarily the patient’s registered practice)

See ticket - https://github.com/nhsconnect/gpconnect/issues/570

**Comment by AndrewGuiseley** [comment]
**Manual tests**
Updated FAPM-73 - Patient Managing Organization to state that this shall be returned and this may not necessarily be the patients registered practice

**Comment by rbutterf** [comment]
test suite includes tests for Patient.managingOrganization being populated and resolvable
