### ISSUE TITLE
Foundations - Register a patient requirements clarifications (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#123]
•Improve register a patient requirements: •Clarify field population requirements for consumers
•Clarify provider responsibilities with respect to: •PDS interaction
•duplicate record prevention
•and local record requirements.

See ticket https://github.com/nhsconnect/gpconnect/issues/553

**Comment by rbutterf** [comment]
added tests for deceased/sensitive/duplicated/inactive/superseded Patients

**Comment by AndrewGuiseley** [comment]
Have added the following manual tests:

RAPTM-28 - Patient matching index checks - matching patient is found
RAPTM-29 - Patient matching index checks - matching patient is not found 
RAPTM-24 - GMS patient creation or re-activation
RAPTM-25 - Local registration - new temporary active record
RAPTM-26 - Local registration - temporary record synchronisation
RAPTM-8 -  Local registration - reactivated record
RAPTM-30 - nhsCommunication extension
RAPTM-31 - managingOrganization - current
