### ISSUE TITLE
Appointments - Organization resource in Search For Free Slots Bundle (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#124]
•Add known issue relating to returned Organization resource in Search for free slots Bundle not being supported by a corresponding _include request parameter
•Add requirement for providers to support the _include:recurse=Location:managingOrganization parameter in preparation for future fix.
•Add requirement for providers to continue to return the Organization, regardless of parameters, except where no slots are returned in the Bundle
•Add requirement for consumers to NOT populate the above parameter at the current time.

See ticket - https://github.com/nhsconnect/gpconnect/issues/559

**Comment by rbutterf** [comment]
added test with parameter  _include:recurse=Location:managingOrganization

**Comment by AndrewGuiseley** [comment]
No impact on manual tests
