### ISSUE TITLE
Foundations - Uplift CapabilityStatement version number to 1.2.2

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#125]
Change the version number in the CapabilityStatement to 1.2.2 in line with new specification release

See ticket https://github.com/nhsconnect/gpconnect/issues/576

**Comment by AndrewGuiseley** [comment]
**Manual tests**
No update needed

**Comment by rbutterf** [comment]
changed app.config -  <add key="gpConnectSpecVersion" value="1.2.2" />
