### ISSUE TITLE
Foundations - Patient contacts (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#126]
Elaborate requirements for Patient.contact

See ticket https://github.com/nhsconnect/gpconnect/issues/583

**Comment by rbutterf** [comment]
Added test for Patient.contact.relationship.text 
tests already exist for contact -name, gender, telecom, address, use, organization

**Comment by AndrewGuiseley** [comment]
Amended following manual tests:

FAPM-55 - Patient contact relationship to state that only the relationship.text element should be populated
RAPM-55 - Patient contact relationship to state that only the relationship.text element should be populated
