### ISSUE TITLE
Access Record Structured - Implement medication date filter (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#127]
Implement new medication date filter logic based only on a start date, in order to always return 
medications that are active on the current date

See tickets:
https://github.com/nhsconnect/gpconnect/issues/572
https://github.com/nhsconnect/gpconnect/issues/577
https://github.com/nhsconnect/gpconnect/issues/582

**Comment by rbutterf** [comment]
test suite already caters for this...need to remove end date set tests

**Comment by rbutterf** [comment]
Changed medicationDatePeriod parameter name to medicationDateFilterStart

**Comment by rbutterf** [comment]
amended to use date format not Period for filter parameters

**Comment by AndrewGuiseley** [comment]
Amended MSM-12 - effective period test as per updated guidance
