### ISSUE TITLE
Access Record Structured - List & Bundle meta.profile cardinality (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#128]
Change meta.profile element cardinality to 1..* for CareConnect-GPC-List-1 and GPConnect-StructuredRecord-Bundle-1

See tickets:
https://github.com/nhsconnect/gpconnect/issues/578
https://github.com/nhsconnect/gpconnect/issues/557

**Comment by rbutterf** [comment]
test suite already caters for this
