### ISSUE TITLE
Access Record Structured - Add Access Record Structured error handling scenarios (1.2.2)

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#129]
•Add additional error handling scenarios:

•the patient has dissented to sharing their clinical record
•the request is for the record of an inactive or deceased patient
•the request is for the record of a non-Regular/GMS patient (i.e. the patient’s registered practice is somewhere else)

See ticket - https://github.com/nhsconnect/gpconnect/issues/580

**Comment by rbutterf** [comment]
added tests for deceased, sensitive, inactive
