### ISSUE TITLE
Update JWT validation tests to remove validation of element

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#13]
In the test suite we have validation for the JWT resource claims for ids and content. This needs re-evaluating after emis integration issues, it highlighted problems with too tight validation where the resources did not include an id or identifier as non were relevant.

Update JWT validation tests to remove validation of element such as ID in the different claim resources. We should reduce it back to checking it is the correct resource type.

For the patient resource we could check that if an NHS Number is included that it is a valid NHS Number but need to discuss this to see if we want to.

**Comment by Chrisjobling** [comment]
The JWT tests have been changed to fit in with the new specification
