### ISSUE TITLE
List expected error codes for Register a Patient & Retrieve a patient’s structured record - 1.2.2

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#133]
Add error codes for Register a patient & Retrieve a patient’s structured record

Pages changed:
•Register a patient ◦
Add expected error codes associated with errors

•Retrieve a patient’s structured record ◦
Add expected error codes associated with errors

•Error handling guidance ◦
Add DUPLICATE_REJECTED error

**Comment by AndrewGuiseley** [comment]
For Register Patient have added the following test:

RAPTM-1 - Error handling

**Comment by AndrewGuiseley** [comment]
Still to look at structured manual tests to re-opening

**Comment by rbutterf** [comment]
ref #129 .. added added tests for deceased, sensitive, inactive
