### ISSUE TITLE
Foundations test suite - passing invalid additional elements test (Register Patient) 

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#136]
The Register patient with additional valid elements currently passes the following extra elements and expects the registration to be successful:

 Active   
 Address      
 Name         
 Births        
 CareProvider  
 Contact       
 ManagingOrg   
 Marital       
 Telecom       

This is incorrect as per the https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html use case where it lists the elements that should be populated - any extra elements MUST NOT be populated (with the exception of Name, Address and Telecom). The other elements in the list above need to be removed

**Comment by rbutterf** [comment]
removed from test 
added
Scenario Outline: Register patient with invalid additional valid elements

**Comment by AndrewGuiseley** [comment]
No impact on manual tests

**Comment by AndrewGuiseley** [comment]
Closed
