### ISSUE TITLE
Test suite - Register Patient - testing around contact point consumer details

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#138]
Ticket raised to look at the requirements on the Payload request body on the Register Patient use case (https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#payload-request-body) to potentially add scenarios to the test suite regarding the patients contact and address details as provided by the Consumer

**Comment by rbutterf** [comment]
added multiple tests for telecom use home, work ,mobile, temp and email

**Comment by rbutterf** [comment]
demonstrator needs changing to allow telecom use values
