### ISSUE TITLE
Check the JWT has a correct 'header part' as per the spec

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#140]
The demonstrator (both versions) is having a check added to ensure the JWT header part is correctly populated as per the spec:

https://github.com/nhsconnect/gpconnect-demonstrator/issues/155

To make sure that the provider test suite continues to function without problem, this ticket is to verify that the test suite is indeed sending the 'header part' through correctly, and if not, to add this in.

The correct header part looks like this (before being encoding):

{
  "alg": "none",
  "typ": "JWT"
}

**Comment by rbutterf** [comment]
The test suite does send the header part 
{
  "alg": "none",
  "typ": "JWT"
}
eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL0NvbnN1bWVyU3lzdGVtVVJMIiwic3ViIjoiMSIsImF1ZCI6Imh0dHBzOi8vYXV0aG9yaXplLmZoaXIubmhzLm5ldC90b2tlbiIsImV4cCI6MTU0MDIwMDEyMiwiaWF0IjoxNTQwMTk5ODIyLCJyZWFzb25fZm9yX3JlcXVlc3QiOiJkaXJlY3RjYXJlIiwicmVxdWVzdGluZ19kZXZpY2UiOnsicmVzb3VyY2VUeXBlIjoiRGV2aWNlIiwiaWQiOiIxIiwiaWRlbnRpZmllciI6W3sic3lzdGVtIjoiR1BDb25uZWN0VGVzdFN5c3RlbSIsInZhbHVlIjoiQ2xpZW50In1dLCJ0eXBlIjp7ImNvZGluZyI6W3sic3lzdGVtIjoiRGV2aWNlSWRlbnRpZmllclN5c3RlbSIsImNvZGUiOiJEZXZpY2VJZGVudGlmaWVyIn1dfSwibW9kZWwiOiJ2MSIsInZlcnNpb24iOiIxLjEifSwicmVxdWVzdGluZ19vcmdhbml6YXRpb24iOnsicmVzb3VyY2VUeXBlIjoiT3JnYW5pemF0aW9uIiwiaWQiOiIxIiwiaWRlbnRpZmllciI6W3sic3lzdGVtIjoiaHR0cHM6Ly9maGlyLm5ocy51ay9JZC9vZHMtb3JnYW5pemF0aW9uLWNvZGUiLCJ2YWx1ZSI6IkdQQ0EwMDAxIn1dLCJuYW1lIjoiR1AgQ29ubmVjdCBBc3N1cmFuY2UifSwicmVxdWVzdGluZ19wcmFjdGl0aW9uZXIiOnsicmVzb3VyY2VUeXBlIjoiUHJhY3RpdGlvbmVyIiwiaWQiOiIxIiwiaWRlbnRpZmllciI6W3sic3lzdGVtIjoiaHR0cHM6Ly9maGlyLm5ocy51ay9JZC9zZHMtdXNlci1pZCIsInZhbHVlIjoiR0NBU0RTMDAwMSJ9LHsic3lzdGVtIjoiTG9jYWxJZGVudGlmaWVyU3lzdGVtIiwidmFsdWUiOiIxIn1dLCJuYW1lIjpbeyJmYW1pbHkiOiJBc3N1cmFuY2VQcmFjdGl0aW9uZXIiLCJnaXZlbiI6WyJBc3N1cmFuY2VUZXN0Il0sInByZWZpeCI6WyJNciJdfV19LCJyZXF1ZXN0ZWRfc2NvcGUiOiJwYXRpZW50Lyoud3JpdGUifQ.

as decoded from bearer token using jwt.io
