### ISSUE TITLE
Appointments: AppointmentType

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#141]
The [GP Connect Appointment definition](https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1) does not allow the appointmentType coding. This will be fixed in the demonstrator in [ticket 157](https://github.com/nhsconnect/gpconnect-demonstrator/issues/157).

Check that any appointment resources created meet the above profile and correct where necessary. This will need to be done for all appointment calls.

Additionally, ensure that any appointments test do not expect the appointmentType coding and will pass when this is not included in the resource. Possibly include tests to ensure that this is not included?

**Comment by rbutterf** [comment]
Test suite already tests for appointmentType not being present in returned resource from Provider system

**Comment by rbutterf** [comment]
added test Scenario: Book appointment with typeCode in appointment resource

**Comment by rbutterf** [comment]
All Book appointments are still passing in the AppointmentType - need to be removed
