### ISSUE TITLE
Slots: ServiceType Coding

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#142]
The [GP Connect Slot definition](https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Slot-1) does not allow the servicetype coding. This will be fixed in the demonstrator in [ticket 158](https://github.com/nhsconnect/gpconnect-demonstrator/issues/158).

Check that any slot resources created meet the above profile and correct where necessary.

Additionally, ensure that any slots test do not expect the serviceType coding and will pass when this is not included in the resource. Possibly include tests to ensure that this is not included?

**Comment by rbutterf** [comment]
Test suite already tests for slotType not being present in returned resource from Provider system
