### ISSUE TITLE
Appointments - request to add a test where the search filter of Org Code or Org Type is not passed in by the Consumer - Search for free slots

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#143]
Request to add a test to check the Provider response when the Consumer does not pass a search filter (Org Type and ODS code) as part of the Search for free slots search parameters.

In this instance the slots returned should be:
Are marked as GP Connect bookable 
AND have no organisation type restriction set 
AND have no organisation/organisation group restriction set

See https://nhsconnect.github.io/gpconnect/appointments_slotavailabilitymanagement.html for more info

**Comment by rbutterf** [comment]
added test to search4slots with no search filter

**Comment by rbutterf** [comment]
needs demonstrator changes
