### ISSUE TITLE
Automated test pack - ability to remove flagged patients from been randomly selected

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#144]
This request is to check whether for patients that have been marked as sensitive/deceased/superseded etc as part of the test data set up can be removed from selection when executing the Foundations and Appointments test suite

Currently as the test suite selects a random patient for each test there are occasions when a flagged patient will be selected which will in turn almost certainly cause the test to incorrectly fail.

**Comment by rbutterf** [comment]
amended random patients to remove deceased/superseded
