### ISSUE TITLE
Automated test pack - amend cancellation reason for a future booked appointment

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#145]
This is a request to check whether a test can be created to check for the following scenario:

If the consumer attempts to amend an appointment updating the cancellation reason only for a future booked appointment (i.e. status equals booked) then an Operation Outcome should be returned

**Comment by rbutterf** [comment]
added test to add extension https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-AppointmentCancellationReason-1 with reason set to douuble booked

demonstrator needs changing
