### ISSUE TITLE
Automated test pack - Register patient with Address Telecom and multiple nhsCommunication - incorect HTTP code

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#149]
For the Register Patient Register patient with Address Telecom and multiple nhsCommunication test the HTTP code that is expected to be returned is 400.

However it looks as though this should be 422, as this would align better with the spine error code of INVALID_RESOURCE

**Comment by rbutterf** [comment]
amended test for 422

**Comment by rbutterf** [comment]
demonstrator needs changing
