### ISSUE TITLE
Hotfixes - Foundations_RC3_Appointments_RC2

### ISSUE THREAD

**Issue by haydenanswer** [nhsconnect/gpconnect-provider-testing#15]
### Current Release (1.0.5)
You can find the most recent release [here](https://github.com/nhsconnect/gpconnect-provider-testing/releases/tag/Foundations_RC3_Appointments_RC2_1.0.5).

You can also compare the changes in **develop** since that release [here](https://github.com/nhsconnect/gpconnect-provider-testing/compare/Foundations_RC3_Appointments_RC2_1.0.5...develop)

### Hotfixes

This issue was created to log the changes made in **hotfix** branches off **master** and merged back in to **develop**. 

For now, we will be periodically tagging releases instead of tagging a new release for every **hotfix**.

This issue will be updated when a new release has been tagged.

*20/11/2017 - 26/11/2017*

* **88cfa73**
* **3c73363**
* **c2de9cc**
* **5e6bec7**
* **c42acbb**
* **cd605d6**
* **566590e**
* **da29c23**
* **51b130f (1.0.3)**

*20/11/2017 - 03/12/2017*

**Comment by james-answer** [comment]
Additional hot fixes have been done since this hotfix so closing the issue.
