### ISSUE TITLE
Test Suite - Structured - clarification requested for medication date tests

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#150]
Provider has reported that 'a number of tests are testing against end date/ time period, etc, whereas the new spec only specifies “MedicationSearchFromDate”.

Clarification requested

**Comment by rbutterf** [comment]
test suite was amended github ref 127 RMB 5/11/2018 to replace medicationDatePeriod with medicationSearchFromDate (and remove end date from searchparameters)
