### ISSUE TITLE
Test suite - clarification requested on the meta.versionid element

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#151]
Provider has the following query:

'It appears that entries in a bundle do not require a VersionId, however the test harness requires to have it set. Could you please confirm which resources should be setting the meta.versionId?'

**Comment by rbutterf** [comment]
For Allergies & Meds it should be null 
But for Foundations + Appts it should be set to a value 
And null for the Bundle
