### ISSUE TITLE
Automated test pack - Register Patient - Register patient with Address Telecom and nhsCommunication

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#153]
Request to insert a check that when the Consumer submits the nhscommunication extension detailing the patients language and interpreter required and the Provider does not return the extension information in the response that an error is raised.

At the moment it appears that so long as a 200 is returned by the Provider then the test passes

**Comment by rbutterf** [comment]
Added test to validate nhsCommunication extension is returned
