### ISSUE TITLE
Automated test pack - Register Patient - request to create a test submitting multiple valid addresses

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#154]
Currently there doesn't appear to be a Register Patient tests that tests the scenario whereby a Consumer submits multiple valid addresses i.e. with a use type of home and work.

This should be allowable and the Consumer should store and return these details, please see https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html

**Comment by rbutterf** [comment]
Added Scenario: Register patient with Multiple Address and Telecom resources

demonstrator needs updating to allow multiple address
