### ISSUE TITLE
Automated test pack - Book Appointment - appt bookng with a different Org Type to what is returned in the SFS call

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#156]
Request to confirm whether it is possible for an automated test to be written for the scenario whereby a Consumer attempts to book an appointment using an Org Type that is different to what is returned in the Search for free slots call

*Just raised for confirmation/clarity as l don't think this is possible to automated

**Comment by rbutterf** [comment]
Provider systems unable to keep state between interactions so unable to automate the test
