### ISSUE TITLE
Automated test pack - Amend appt - scenario where comment is amended for Providers that support only the Description

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#157]
Request to see whether it is viable to produce an automated test for the following scenario:

Test to check that if a Provider only supports the mandatory description element and not the comment element, if a comment is received as part of the amend API call then the provider should append the content of the comment to the description within the appointment so that the additional information is not lost.

**Comment by rbutterf** [comment]
Added Scenario: Amend appointment with Comment and Description
