### ISSUE TITLE
Return minimal tests, check that the content length is zero and ignore the content type

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#16]
Currently for the tests which check that return minimal prefer header returns no payload we check that the content length is zero but also check there is no content type.

The SSP is adding in a content type of "html/text" causing the tests to fail. We should remove the check that the content type header does not exist as long as the content length header is zero.

**Comment by Chrisjobling** [comment]
Fixed, this has been released to latest version
