### ISSUE TITLE
Possible appointment booking improvement.

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#18]
Current each test run appointments are booked against the same patient. If we randomise the patient used, ie. randomly changed the patient used for appointment booking tests for each test run, but make sure if we have set a patient which should not have any appintments that they are not included in the random patient selection.

This will possibly reduce the number of appointments booked for a single patient but may make debugging a test more difficult so should be configurable to be switched off.

**Comment by Chrisjobling** [comment]
Users now have the ability to randomise patients
