### ISSUE TITLE
Register patient - work and old addresses

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#180]
In line with spec change [nhsconnect/gpconnect#620](https://github.com/nhsconnect/gpconnect/issues/620) -

Consumers can no longer send addresses with a 'use' value of 'work' or 'old' into Register Patient.

If a value of 'work' or 'old' is sent, the response should be a 422/INVALID_RESOURCE.

**Comment by rbutterf** [comment]
add tests for multiple combinations of work / old
