### ISSUE TITLE
Amend a cancelled appointment is no longer allowed

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#182]
In line with spec change:

[nhsconnect/gpconnect#601](https://github.com/nhsconnect/gpconnect/issues/601)

Amending a cancelled appointment is no longer allowed.

If an appointment with a status of cancelled is amended, the demonstrator should return a 422 / INVALID_RESOURCE error.

Cancellation reason can no longer be amended (as this could only be amended when the appointment was cancelled).

Suggest tests to check that 422 / INVALID_RESOURCE is returned when amending a cancelled appointment.

**Comment by rbutterf** [comment]
Added Scenario: Amend a cancelled appointment
