### ISSUE TITLE
Account for clock skew when determining JWT timing validation

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#188]
**Unfortunately the specified solution for this item has changed, ignore this description and see the comment further down the page.  Apologies this may need some rework.**

---

In order to test the following spec change:

https://gpconnect-1-2-3.netlify.com/integration_cross_organisation_audit_and_provenance.html#exp-expiry-claim

nhsconnect/gpconnect#640

Suggest the following tests are run (with no/minimal clock skew between test suite server and provider server):

1.  Everything normal test - Send a token with iat = now, ensure OK.
2.  Ensure token expiration check (10 mins old)- Send a token with iat = now-600s, ensure FAIL.
3.  Ensure token future date check (10 minutes in future) - Send a token with iat = now+600s, ensure FAIL.

Now check for clock skew allowance:

4.  Consumer clock is fast 90s (inside clock skew leeway) - Send a token with iat = now+90s, ensure OK.
5.  Consumer clock is fast 180s (outside clock skew leeway) - Send a token with iat = now+180s, ensure FAIL.
6.  Consumer clock is slow 90s (inside clock skew leeway) - Send a token with iat = now-90s, ensure OK.
7.  Consumer clock is slow 390s (still inside clock skew leeway) - Send a token with iat = now-390s, ensure OK.
8.  Consumer clock is slow 480s (outside clock skew leeway) - Send a token with iat = now-480s, ensure FAIL.

Last two tests are 390s (5 minutes + 90s) and 480s (5 minutes + 180s) to account for the 5 minute expiry time on the token.

**Comment by jonnyry** [comment]
https://github.com/nhsconnect/gpconnect/issues/640

**Comment by rbutterf** [comment]
added 8 extra tests in the JWT feature file

**Comment by jonnyry** [comment]
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#minimise-likelihood-of-rejected-tokens-due-to-clock-skew
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/640
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/222
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/188

**Comment by jonnyry** [comment]
After discussion within the programme, and across NHS Digital, the agreed position is:

- Providers shall reject tokens that have expired (e.g. validate the exp claim)
- Providers and consumers shall synchronise their clocks with NTP servers
- Providers shall not validate the iat claim (iat was originally included for validation however was rejected on review) or validation the duration between iat and exp

Therefore the testing in the description unfortunately isn't valid any longer and will need changing to check that only expired JWTs are rejected (exp <= current date).  JWTs that now appear to be in the future (iat > current date) are considered valid by the provider API.
