### ISSUE TITLE
(**Un-)Relax test for cross care setting identifier 

### ISSUE THREAD

**Issue by mstephens-xsl** [nhsconnect/gpconnect-provider-testing#190]
**This change has been reverted, the description below is no longer accurate - please see comment 9-Apr-2018 further down**

---

The provider suite needs to be updated to reflect the change to cross care setting identifiers specified in this ticket:

[Issue #644](https://github.com/nhsconnect/gpconnect/issues/644)

The suite should no longer test that a cross care setting identifier is always present on the MedicationStatement, MedicationRequest and AllergyIntolerance resources. Instead, it could test that where one has been specified (_system = 'https://fhir.nhs.uk/Id/cross-care-setting-identifier'_) it is a GUID.

**Comment by rbutterf** [comment]
relaxed tests for MedicationStatement, MedicationRequest and AllergyIntolerance resources

**Comment by jonnyry** [comment]
The change has been reverted - so cross care setting identifier remains MANDATORY.

Please could revert the tests as such.

**Comment by PeterGresty** [comment]
change reverted and only fixed guid check code left
