### ISSUE TITLE
Create new test set for 0.7.x

### ISSUE THREAD

**Issue by tim1ford** [nhsconnect/gpconnect-provider-testing#191]
0.7.1 has now been released and needs the corresponding test suite available.

Both release notes from 0.7.0 and 0.7.1 will need to be addressed:

https://developer.nhs.uk/apis/gpconnect-0-7-1/overview_release_notes_0_7_0.html
https://developer.nhs.uk/apis/gpconnect-0-7-1/overview_release_notes_0_7_1.html

**note:** 0.7.2 is in the process of being published and contains the same JWT changes introduced in 1.2.3

**Comment by Sado1234** [comment]
Tickets have been raised separately for 0.7.0 and 0.7.1 changes
This ticket is not required
