### ISSUE TITLE
S-Flag patients to return Patient Not Found in ARHTML

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#192]
version 0.5.0 of ARHTML HTML implementation standards states that demographic details are to be redacted for patients which are S-flagged on Spine e.g. ‘May be redacted if patient is flagged on Spine as Sensitive demographics.’ This has been queried and subsequently changed in other capabilities for providers not to return patient records for S-flagged patients but to return a ‘Patient Not Found’ error.

**Comment by PeterGresty** [comment]
Change implemented Ticket Closed
