### ISSUE TITLE
Default Date Range Banner Message Wording

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#194]
change default date range banner message wording

**Comment by Sado1234** [comment]
Approach plan: 
Make text changes in htmlSteps.cs file as per spec to:
<div class="date-banner">
	<p>All relevant items</p>
</div>

Add a test to Html Feature 'should contain the default banner' to check null values in StartDateTime and EndDateTime, existing tests will cover no date values provided.

**Comment by Sado1234** [comment]
Change implemented Ticket Closed
