### ISSUE TITLE
Clarify acceptable usage of sub-section banners and uplift the specification

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#195]
the layout of sections and subsections has been standardized to avoid supplier variance

**Comment by Sado1234** [comment]
Layout   section | 0.7.2 Spec | Action
-- | -- | --
Section and SubSection Content Banner | Changed   to MUST have | Check   covered under Manual Test
Date Banner | Changed   to MUST have | No action required as covered by test: "filtered sections should contain date range   section banner"
GP transfer banner | No   change in spec from 0.5.2 - 0.7.2 | None
Exclusion Banner | Changed   to MUST have | Check   covered under Manual Test

**Comment by Sado1234** [comment]
Tests added to automation test suite on feature/0.7.2. Also raised manual tests on HTML01 and HTML02 to cover checks where automation not possible.
