### ISSUE TITLE
Medication Issues

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#197]
•Current Medication Issues has been replaced by Recent Acute Medications
•The following list of subsections now comprises the Medication view: •Recent Acute Medication
•Current Repeat Medication
•Discontinued Repeat Medication
•All Medication (Summary)
•All Medication Issues

**Comment by Sado1234** [comment]
Not sure if this is intentional but the Example view in CodePen doesn't match that of the updated HTML.

**Comment by Sado1234** [comment]
Amended tests 'html section headers present' and 'sections should return no data available html banner' to assert the below headers:
Recent Acute Medication
Current Repeat Medication
Discontinued Repeat Medication
All Medication (Summary)
All Medication Issues

**Comment by Sado1234** [comment]
Code implemented closing ticket
