### ISSUE TITLE
Current is not explicitly defined for medication subsection content

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#199]
each subsection now contains greater detail as to what is being displayed

**Comment by SimonFarrowNHS** [comment]
Not clear to me how this affects either provider tests or demonstrator

**Comment by Sado1234** [comment]
Further explanation from Martin Hillyard
We used to have two 'current' sections in medications which were Current Medication Issues and Current Repeat Medications
The latter was fairly well understood by providers and appears to be quite consistent, but the former was all over the place

The former not only had problems with inconsistency over current, but also the meaning of issues and how that overlapped with Current Repeat
So we have replaced Current Repeat Issues (as in 0.5.x) with Acute Medication Last 12 Months in 0.7.x - or similar name

Where Current Repeat Issues was intended as mix of Acute and Repeat with Current undefined; it is now just Acute Meds and the scope should be defined now to
Start Date (the date the prescription is expected to start) is greater than the current date minus 365 days. 

Test against - Recent Acute Medication - query if this should be manual checks
Check values being populated in the correct field - again query if manual tests

**Comment by Sado1234** [comment]
Manual test created refer to Views-5.1
