### ISSUE TITLE
JWT mandatory field and validation clarification

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#2]
Within the specification page for the JWT:

https://nhsconnect.github.io/gpconnect/integration_cross_organisation_audit_and_provenance.html

There are three main problems with the level of detail on this page:
* The mandatoray fields required within the FHIR resources are not clear
* The required validation for the contents of the JWT and what error codes should be returned if the validation fails.

Error Responses:
* Any validation failure has currently be set to expect a http 400 error response code and we are not checking for an OperationOutcome. Do we want to expect and OperationOutcome?

So far we have set out tests to make sure the JWT contains the following:
* Creation time should not be in the future
* Expiry time should be exactly 5 minutes after the creation time
* All the fhir resources in the JWT should be valid fhir resources.
* Requesting organization resource contains a identifier of type ODS code
* Practitioner resource contains as identifier or type SDS code
* Requesting practitioner ID must match the id in the practitioner fhir resource
* The practitioner resource should contain a family name and given name
* The practitioner resource must contain an SDS Job Role code
* The provider must check that all the required claims are present and contain the fixed value if set out in the table.
* The request url should be matched to the request_scope claim where possible. For example the gpc.getCareRecord request should be request_scope of "patient/*.read".
* For the getCareRecord request the patient NHS Number in the requested_resource should match the NHS number in the getCareRecord request payload.
* The request_scope should be one of the four acceptable types.

The JWT page also needs updating to include informaiton on the header content and the base64 encoded final Bearer token, including:
* JWT header needing to use "alg" or type "none"
* No signiture element on the bearer token, until authentication and RBAC is implemented at a later date.

**Comment by michaelmeasures** [comment]
Hi @james-answer on the last couple of points it's already been updated to include details of the three standard JWT sections, the usage of the 'none' algorithm in the header and the empty signature block.

**Comment by james-answer** [comment]
As the JWT is the is in the Authorization header if validation fails should the response error code be a 403 rather than a 400.

**Comment by michaelmeasures** [comment]
Hi @james-answer if it's missing I think it should likely be a 401. If it's there but not valid then think a 400 is okay, when we get to checking claims then that will definitely be a 403.

**Comment by michaelmeasures** [comment]
Looks like we should broadly align with https://tools.ietf.org/html/rfc6750 which outlines when to use 400 vs. 401 vs. 403.

invalid_token
         The access token provided is expired, revoked, malformed, or
         invalid for other reasons.  The resource SHOULD respond with
         the HTTP 401 (Unauthorized) status code.  The client MAY
         request a new access token and retry the protected resource
         request.

I would interpret this as the JWT malformed at the most fundamental level i.e. doesn't deserialize or is corrupted.

**Comment by michaelmeasures** [comment]
Closing out this issue as specification changes are to be handled under the main 'gpconnect' issues section. Note, I've recently added a link to RFC 6750 to help standardize the error codes around the oAuth bearer token,
