### ISSUE TITLE
Summary page - reordering of sections

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#201]
New layout of Summary page based on FoT feedback and Medications updates:
Last 3 Encounters
Active Problems and Issues
Current Allergies and Adverse Reactions
Recent Acute Medication
Current Repeat Medication

**Comment by Sado1234** [comment]
Made changes to the ordering, section titles plus changes to the column headers for each section against the relevant tests in the Html.feature.

**Comment by Sado1234** [comment]
Code implemented closing ticket
--
