### ISSUE TITLE
Appointments - description and comment field character limits

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#203]
Add new tests for the following

For Book and Amend Appointments :- 

Providers shall support storing the limits of 100 characters (description field) and 500 characters (comment field)

Providers shall not truncate description or comment fields when storing in their system

Providers shall return an error where consumers send more data than can be stored by the provider

#625 https://github.com/nhsconnect/gpconnect/issues/625

**Comment by PeterGresty** [comment]
added tests to check boundaries of description and comment fields as per specs above

**Comment by jonnyry** [comment]
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#book-appointment---description-and-comment-field-character-limit-handling-clarification
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/625
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/221
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/203

**Comment by jonnyry** [comment]
This one is a little tricky - we've previously agreed with two of the providers that they can accept greater than the limits above (up to their system limit), as long as they are not truncating data.  So for example 600 in comment field, and 200 in description field.

This makes it trickier to test (without a manual test)...

Suggest:

- test sending description of 100 and comment of 500, then read appointment and check the results match
- test sending description of 101 and comment of 501, either of the following are acceptable responses:
  - error response
  - success response but ensure the system has stored the information by re-reading the appointment and checking for the full description and comment
- test with a big description and comment (10000 chars?) beyond the provider system limits (we'll need to check this with them) and check an error response is returned

The important thing is that data is never truncated
