### ISSUE TITLE
ARHTML Medications - Minor alterations to wording

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#204]
Minor uplifts to Medications

see #622

**Comment by Sado1234** [comment]
**SA action** required from #622
- write automation tests for MUST have text in Subsection - content banners (this ticket only refers to the one subsection) refer to table below of changes from 0.5.2

0.5. | Content banners | 0.7. | Content Banners   - relevant records Providers MUST return message
-- | -- | -- | --
Current   Medication Issues | none | Acute Medication   (Last 12 Months) | <div>     	<p>Scheduled End Date is not always captured in the source; where it   was not recorded, the displayed date is calculated from start date and days   duration</p>     </div>
Current   Repeat Medications | not all provide   message | Current Repeat   Medication | <div>     	<p>The Review Date is that set for each Repeat Course. Reviews may   be conducted according to a diary event which differs from the dates   shown</p>     </div>
Past   Medications | none | Discontinued Repeat   Medication | <div>     	<p>All repeat medication ended by a clinician action</p>     </div>
  |   | All Medication | Message but   not specified
  |   | All Medication Issues | Message but not   specified

- All header changes have been implemented under #197

**Comment by Sado1234** [comment]
Closing this ticket as the only change for test suite relates to a content banner change that is covered under #195
