### ISSUE TITLE
Separate Major Inactive Problems and Issues into a separate subsection

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#209]
The problems and issues view therefore requires uplifting to separate the content of the inactive problems and issues into two subsections
•Major Inactive Problems and Issues
•Other Inactive Problems and Issues

Supporting definition of major to be included along with definitions for handling no significance for individual records or provider systems not supporting significance levels which meaningfully translate to Major / Minor

see #629

**Comment by Sado1234** [comment]
Ammended test sections should return no data available html banner to cinfirm change, this was done under #201 commit
https://github.com/nhsconnect/gpconnect-provider-testing/commit/03a19d26be7f8fc2c13b4803a6992c76ce0accee
