### ISSUE TITLE
Default date range if only a start or end date parameter passed in getCareRecord

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#215]
•the scenario where only a start or an end date need to be considered and the GP Connect program needs to update the specification to cater for the possibility of someone only sending a start date or an end date

•date banner section uplifted to add more clarity on expected date range behaviours

**Comment by Sado1234** [comment]
Added in tests to Html.feature 
"should contain the applied start banner" and "should contain the banner All data items until" and added in HtmlSteps to assert the expected banners

Wait on code to confirm tests

**Comment by Sado1234** [comment]
Code committed closing ticket
