### ISSUE TITLE
Default Date Range Banner Message Wording

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#216]
•change default date range range banner message wording.

**Comment by Sado1234** [comment]
Added test to Html.feature 
"check when no date range supplied should contain default date range section banner"
and amended HtmlSteps.cs to html.ShouldContain("<p>All relevant items</p>")

Wait on code to confirm test

**Comment by Sado1234** [comment]
Need to back this change out of feature/0.5.2 as spec states 'SHOULD' be provided not a 'MUST'

**Comment by Sado1234** [comment]
Tweaked HtmlSteps mehtod - ThenTheResponseHTMLShouldContainTheAllDataItemsText to assert SHOULD text for 0.5.2 being either:
"<p>All relevant items</p>"  OR
"<p>All relevant items subject to patient preferences and / or RCGP exclusions</p>"

**Comment by Sado1234** [comment]
Code committed closing ticket
