### ISSUE TITLE
Access Record HTML format

### ISSUE THREAD

**Issue by rbutterf** [nhsconnect/gpconnect-provider-testing#217]
•in the ‘HTML Views’ pages there are ‘HTML View’ sections which show how the HTML should be formatted for all the sections.

these have always been treated as part of the spec, indicating the proposed tag format and structure for the HTML. It was raised that this is not clear and should be updated to specifically say that the format and tags should be followed for the HTML structure.
•Encounters
•Clinical items
•Problems and issues
•Allergies and adverse reactions
•Medications
•Referrals
•Observations
•Immunisations
•Administrative items

**Comment by tim1ford** [comment]
These items have been covered in more detail across other git issues.
