### ISSUE TITLE
Improve clarity of JWT population page for new consumers

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#224]
- Check that the JWT **sent** in the 1.x test suite is in line with the improved guidance on:

https://gpconnect-1-2-3.netlify.com/integration_cross_organisation_audit_and_provenance.html#jwt-payload

- Also add some explicit tests around the JWT to check when sending the `requesting_practitioner` claim:
  - that if the last two `identifier` elements (SDS role profile ID and local identifier) are not present, the provider API still accepts the JWT
  - that the SDS user ID and SDS role profile ID can be sent as UNK and the provider API will accept them

- As the improvement in guidance to the spec is for consumers only and we are not expecting providers to make changes based on this, suggest no other changes to the tests, other than:
  - checking the JWT sent as part of the test suite is in line
  - and the explicit tests mantioned above

**Comment by Sado1234** [comment]
Checked that the JWT sent in the 1.2.3 test suite is in line with the improved guidance on the JWT payload.
Added two test scenario’s to cover specific tests into JWTFeature 
•	JWT - Missing sdsRoleProfile and guid
•	JWT - Requesting Identity - UNK value
Also ran regression tests across the hole test suite and confirmed all tests returning as expected

**Comment by Sado1234** [comment]
Changes been pushed into master and now part of release/1.2.3 branch
