### ISSUE TITLE
Organization resource in Search for free slots Bundle

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#225]
Please see the background for this issue:

https://nhsconnect.github.io/gpconnect/appointments_known_issues.html#organization-resource-in-search-for-free-slots-returned-bundle

The test suite should check that:

- sending the `_include:recurse=Location:managingOrganization` parameter does not throw an error (i.e. returns a Bundle containing an organisation)
- but also NOT sending the parameter returns a Bundle containing an organisation - unless there are not slots returned in which case nothing should be in the Bundle

(essentially the parameter should be accepted but ignored by the provider)

The test suite should also check that the parameter is declared on the CapabilityStatement:

- See last point on the release notes:  https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#organization-resource-in-search-for-free-slots-bundle

---
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#organization-resource-in-search-for-free-slots-bundle
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/645
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/216
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/225

**Comment by PeterGresty** [comment]
part 1 covered already by existing Test : Successfully search for free slots and check the included schedule resources returned are valid
part 2 covered already by existing Test : Searching for free slots with org type searchFilter system 
part 3 new test to check capability statement contains
