### ISSUE TITLE
Amending a cancelled appointment is no longer supported

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#226]
Check that if a cancelled appointment is amended, a 422 error with error code INVALID_RESOURCE is returned.

---
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#amending-a-cancelled-appointment-is-no-longer-supported
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/601
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/219
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/226

**Comment by Sado1234** [comment]
The below tests are already set to the expected OperationOutcome - INVALID_RESOURCE. 
Once feature/1.2.3 is stable to run AppointmentCancelFeature will re-run feature.

- Amend a cancelled appointment
- I perform a successful cancel appointment and amend the comment
- I perform cancel appointment and update the description
- I perform cancel appointment and add participants
- I perform cancel appointment and update the type text

**Comment by Sado1234** [comment]
Re-ran tests on feature/1.2.3 and existing test are returning a 422 as expected on Amend a cancelled appointment, refer screenshot
![image](https://user-images.githubusercontent.com/46973626/56124918-a540b280-5f6f-11e9-97f0-4af3969c7333.png)
