### ISSUE TITLE
Some CareConnect-HumanLanguage-1 code system language descriptions do not match the ISO639-2 list

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#227]
Some of the human language descriptions have changed slightly -

Code | Old Description | New Description
-- | -- | --
bh | Bihari | Bihari languages
ii | Sichuan Yi | Sichuan Yi; Nuosu
ps | Pushto | Pushto; Pashto
ro | Romanian | Romanian; Moldavian; Moldovan

These are sent and received in the Patient.extension[nhsCommunication] element:

```
{
      "url": "https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NHSCommunication-1",
      "extension": [
        {
          "url": "language",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-HumanLanguage-1",
                "code": "bn",
                "display": "Bengali"
              }
            ]
          }
        },
        {
          "url": "interpreterRequired",
          "valueBoolean": false
        }
      ]
    }
  ]
```

To test, suggest registering a patient with the languages that have had their description updated, then checking the response (via Read a patient) uses the new description?

(appreciate this might be tricky, and I would prioritise other tickets ahead of this one given the impact of the change is small)

**Comment by jonnyry** [comment]
Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#some-careconnect-humanlanguage-1-code-system-language-descriptions-do-not-match-the-iso639-2-list
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/643
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/220
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/227

**Comment by jonnyry** [comment]
Already tested in TKW validation #189.

Suggest close this one?

**Comment by PeterGresty** [comment]
Russell Added to TKW Rule set closing
