### ISSUE TITLE
Keep alive being sent from test suite

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#23]
When checking SSP logs it was noticed that the keep alive requests kept being made to the provider when the test is running. This would indicate the connection is possibly not being closed correctly.

We need to:
* Try and re-create the issue locally to see if the issue is coming from the test suite.
* Close the connection properly to stop the additional keep alive calls.

**Comment by lucywilcock** [comment]
I have attempted to replicate this locally but haven't been able to see any keep alive messages associated with the tests. Running the tests and monitoring with wireshark showed the HTTP messages being sent to the public demonstrator but no keep-alives. I can see FIN messages being sent and received which would imply that the connection is closed. 

I have checked the code but can't find anywhere that would send a keep-alive or configure a keep-alive header.

James is going to talk to Russel to see if it is the SSP that isn't closing the connection.

I'm closing this issue for now.
