### ISSUE TITLE
Appointment display requirements

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#232]
Check a consumer system is displaying all the fields required to choose and book an appointment (in order that the wrong type of appointment is not booked):

https://developer.nhs.uk/apis/gpconnect-1-2-3/appointments_use_case_search_for_free_slots.html#consumer-display-requirements

**Comment by BabarNHS** [comment]
Following Scripts have been updated  CONS-AppointmentsAPITest1,2 and 3 to validate the following attributes are displayed:-
Start date and time, 
End date and time, or duration,
 Delivery channel (in-person, telephone, video), 
Location name and address, 
Practitioner role (e.g. General Medical Practitioner, Nurse), 
Practitioner name and gender
