### ISSUE TITLE
Check that the UI displays the appointment times correctly when in BST

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#233]
The GP Connect appointment messages represent times using "UK local time", that is the message contains:

`01-01-2019T15:00:00+00:00` is 3pm in winter time (GMT)
`01-07-2019T15:00:00+01:00` is 3pm in summer time (BST)

Ensure the consumer UI is displaying these correctly as per the message and that times have not been shifted forwards or backwards.

**Comment by BabarNHS** [comment]
Updated Test CONS-AppointmentsAPITest1 to be executed twice by the consumer in BST and GMT to ensure UI displays the the times are returned in the message and that the UI does not carry out any Time updates
