### ISSUE TITLE
Ensure consumer systems are time synchronising their servers with the NHS NTP time service

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#234]
Ensure consumer systems are time synchronising their server's clocks with the NHS NTP time synchronisation service.

This ensures that date and times within messages are accurate, and their JWT tokens are not rejected by the provider systems.

**Comment by BabarNHS** [comment]
We do have a requirement the SCAL (Spine Integration Tab) for the consumers to **confirm** that their servers are synced as per requirement:- SSP-01

"All HSCN-connected systems are expected to synchronize their local system clocks to the HSCN Network Time Protocol (NTP) reference source"
