### ISSUE TITLE
Change warning message for patient transfers

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#236]
The text for the warning code for data in transit has been updated:

“Patient record transfer from previous GP practice not yet complete; any information recorded before dd-Mmm-yyyy has been excluded.” 

has been changed to 

“Patient record transfer from previous GP practice not yet complete; information recorded before dd-Mmm-yyyy may be missing.”

**Comment by AndrewGuiseley** [comment]
Updated the warning text in the associated manual test. Closed
