### ISSUE TITLE
Operation Outcome - severity level of anything other than 'error'

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#259]
Request for a possible validation check in TKW or a automated test (which ever is more suitable) to check that Providers should not be returning any Operation Outcome resources with a severity of anything other than 'error' (i.e. not fatal), see the following:

https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html

**Comment by PeterGresty** [comment]
Can be tested in provider test suite, so no change to tkw

**Comment by Sado1234** [comment]
Code committed, closing call
