### ISSUE TITLE
Add in Meta profile in payload request body

### ISSUE THREAD

**Issue by Sado1234** [nhsconnect/gpconnect-provider-testing#269]
EMIS highlighted that the meta.profile is not present in the request payload. Jonny Rylands has confirmed that the meta.profile should be included in the payload. **Not to validate**

(GPConnect-RegisterPatient-Operation-1)

**parameter.resource.meta.profile = "https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1"**

**Current request body**
`
<fhirRequestParameters> {
    "resourceType":"Parameters",
    "parameter":[ {
        "name":"registerPatient",
        "resource": {
            "resourceType":"Patient",
            "identifier":[ {
                "extension":[ {
                    "url":"https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareConnect-GPC-NHSNumberVerificationStatus-1",
                    "valueCodeableConcept": {
                        "coding":[ {
                            "system": "https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-NHSNumberVerificationStatus-1", "code": "01"
..... 
`

**Expected as per Spec (https://developer.nhs.uk/apis/gpconnect-1-2-3/foundations_use_case_register_a_patient.html#payload-request-body)**
`{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "registerPatient",
      "resource": {
        "resourceType": "Patient",
        "meta": {
          "profile": [
            "https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1"
          ]
        },......

**The below API's for Appointments include the meta.profile in the request payload and note will be in the upcoming Advanced Structure_**
Book an Appointment
Amend an Appointment
Cancel an Appointment

"resourceType": "Appointment",
  "meta": {
    "profile": [
      "https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1"
    ]

Relates to demonstrator ticket (https://github.com/nhsconnect/gpconnect-demonstrator/issues/254)

**Comment by RiChallinor** [comment]
Include some tests that do have the profile and some that don't

**Comment by Sado1234** [comment]
The code has been added and committed, not being validated in this version
