### ISSUE TITLE
Foundations - Removal of multiple organisation resources with the same ODS code test

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#275]
The 'Organization search success' test has a scenario where multiple Organisation resources are returned when searching by ODS code

After discussing with the Appointments TA it has been confirmed that this is not a valid scenario. No more than one Org resource should be returned when searching by the only supported (or at least the only one where a successful response can be guaranteed) identifier type of ODS code. Request raised to remove this scenario.

**Comment by PeterGresty** [comment]
Change has been made on a new branch, ready for merging with the other changes

**Comment by PeterGresty** [comment]
code merged into release/1.2.3 and master
