### ISSUE TITLE
Removal of JWT Practitioner Role and SDS Job Role tests from the HTML test suite

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#288]
Request to remove the following JWT tests from the HTML test suite:

JWT requesting practitioner does not contain a practitionerRole
JWT requesting practitioner practitionerRole does not contain a SDS Job Role name

The request to remove the tests stems from the fact that in some cases consumers may not populate the practitionerRole, see https://developer.nhs.uk/apis/gpconnect-0-5-2/integration_cross_organisation_audit_and_provenance.html

**Comment by PeterGresty** [comment]
Changes created on feature branches for 0.5.2 and 0.7 branches. they are ready to be merged into main branch on next release

**Comment by PeterGresty** [comment]
Changes Applied
