### ISSUE TITLE
1.2.4 -Structured (M+A) - Allow more than one warning code in the Extension-CareConnect-GPC-ListWarningCode-1 profile

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#289]
This could either be a automated or manual test - could specify in test prereqs that patient have confidential items and data awaiting filing  

https://github.com/nhsconnect/gpconnect-provider-testing/issues/289

**Comment by PeterGresty** [comment]
Tests created and merged into feature/1.2.4 branch

**Comment by PeterGresty** [comment]
Tests created and code merged
