### ISSUE TITLE
Add check for name and address within location resources

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#29]
Busniness requirements have been uplifted to say that the location should have atleast a name and address element. We need to make sure the tests for:

Read a location
Search for free slots

returns a name and address within the location resource. For Search for free slots the location is only returned if requested with the include parameter.

**Comment by lucywilcock** [comment]
This has been completed in branch location-name-address.

Additional checks are now done in the location/search for slots tests to validate that there is a name and an address on all locations.

**Comment by lucywilcock** [comment]
This has been merged.
