### ISSUE TITLE
Patient resource preferred branch surgery

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#30]
Within a patient resource it should contain a preferred branch surgery within the registration details extension.

We should add a test for all the patient related feature files to check that the returned patient resources contain a preferred branch surgery. This should be done as a seperate test as it is a SHOULD and not a SHALL so it might not be supported by some providers therefore if soultion assurance give it a let we do not want them to give a let on a test which tests more than just this.

**Comment by lucywilcock** [comment]
This has been completed. New tests have been added into PatientRead, PatientSearch and PatientRegister to ensure a patient returned from each includes the preferredBranchSurgery. This is in branch patient-preferred-branch.

Small changes were required in the demonstrator to ensure that the patient read test passed. These changes are in a similarly named branch.

**Comment by lucywilcock** [comment]
This has been merged.
