### ISSUE TITLE
AccessStructuredRecordMedicationsFeature forcing basedOn to be mandatory

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/gpconnect-provider-testing#301]
(On behalf of microtest)

With a response with an authorised request for a drug 
(So MedicationRequest.intent = order). 
Testpack then tests for MedicationRequest.basedOn being populated. This appears to be wrong and unable to find documentation which says otherwise.

**Comment by KevinMayfield** [comment]
After speaking to GP Connect. Realise this issue is in GP Connect spec https://developer.nhs.uk/apis/gpconnect-1-2-4/accessrecord_structured_development_medication_resource_relationships.html

**Comment by PeterGresty** [comment]
Hi Kevin, Can this ticket be closed then?

**Comment by KevinMayfield** [comment]
Yes. May come back to this as we're finding the MedicationRequest model to be quite different to the internal model. (We're having to create planned MedicationRequest from issues)
