### ISSUE TITLE
MedicationRequests Contain Repeat Info only when Repeat or Repeat Dispensing with Intent of Plan

### ISSUE THREAD

**Issue by PeterGresty** [nhsconnect/gpconnect-provider-testing#310]
It has been highlighted by the 1.3.1 testing that the provider test suite is not currently not checking that repeat dispensing medicationrequest's with an Intent of Plan have the repeat Prescriptions Extension. 

Provider test Suite logic needs updating to check for the extension when the medicationRequest is a "repeat" or "repeat dispensing" type, with an intent of Plan.

**Comment by Sado1234** [comment]
Applied the same changes to feature_1.2.4/#311_RevisedForwardCompatability - as per PG changes to 1.3.1 branch

**Comment by Sado1234** [comment]
code committed to both feature branches, feature/1.3.1 and feature 1.2.4 closing ticket
