### ISSUE TITLE
Remove JWT claim "requested_record"

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#32]
We need to remove the JWT claim from all tests and tests for the claim as it has been removed from the specification. This change applies to the following versions of the specificaiton:

1.0.0
1.1.0

The claim can be seen in the old 0.5.0 version of the spec:

https://developer.nhs.uk/apis/gpconnect-0-5-0/integration_cross_organisation_audit_and_provenance.html

but is no longer in the specification from 1.0.0 onwards:

https://developer.nhs.uk/apis/gpconnect-1-0-0/integration_cross_organisation_audit_and_provenance.html

Linked to demonstrator update https://github.com/nhsconnect/gpconnect-demonstrator/issues/44

**Comment by lucywilcock** [comment]
This has been completed and merged with the 1.0.0 and 1.1.0 release branches and tags as well as with develop.
