### ISSUE TITLE
"If-Match" not sent with Cancel Appointment requests

### ISSUE THREAD

**Issue by emileaxelrad** [nhsconnect/gpconnect-provider-testing#324]
For all of the cancellation tests, the If-Match header is not sent along with the PUT request.
This does not appear to behave like a valid Consumer system.

We believe a valid Provider implementation must return a HTTP 409 or 415 error in this scenario.

https://developer.nhs.uk/apis/gpconnect-1-5-0/appointments_use_case_cancel_an_appointment.html
"SHALL return an error if the version identifier in the If-Match header does not match the Appointment’s current version identifier"

**Comment by PeterGresty** [comment]
Hi Emile,

Can you please raise any new issues via team please as we have stopped using this ticket system. I will be asking for a board to be setup, so you can raise tickets which will make it easier to work through any issues you raise but for now put in teams chat along with the others you have raised. Thanks

As for the if-match issue you raised,  we understand that the spec isnt as clear as it could be on this front and Jonny Rylands is going to update the spec to make clearer soon but in the mean time below is a clarification on how to proceed for now.

For PROVIDERS Both Appmts Amend and Cancel the if-match header is optional, So if it is sent , then it should be checked and return a 409 error if it doesnt match. If not sent, then it should just process it regardless. The automated pack has various tests to check each of these scenarios.

Can you confirm you are happy to proceed on basis and I will then close this ticket. Thanks

**Comment by PeterGresty** [comment]
Moved Ticket to Teams, Closing
