### ISSUE TITLE
Step - the allergyIntolerance reaction should be valid

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#35]
For the step "the allergyIntolerance reaction should be valid" the following probably needs updating:

1. The following check is done before we check if allergy.Reaction is null, "allergy.Reaction.Count.ShouldBeLessThanOrEqualTo(1);", this might cause a null pointer exception?

2. The check "allergy.Reaction[0].Manifestation.Count.ShouldBeLessThanOrEqualTo(1);" should probably follow a check to see if "allergy.Reaction[0].Manifestation" is null otherwise we might get an exception.

3. In the spec there is three elements within reaction which should not be populated. We should check that the elements are not populated in this step.

https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_allergyintolerance.html

**Comment by lucywilcock** [comment]
1. The null check is now performed before the count check.

2. There is now a null check for the Manifestation before the count less than or equal to check.

3. The null/empty checks have been moved into the Reaction validity step.
