### ISSUE TITLE
Registration Details - Preferred branch surgery within response

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#37]
The specification has been updated with additional guidance for the preferred branch surgery within the registration details extension.

We need to add a check that the provider always returns a reference to a location within the patient resource on a register patient request. The consumer may choose to include preferred branch surgery or not so we should include tests for both the scenarios where the consumer sends one and where they don't send one. On both we should check that a preferred branch surgery reference is returned. The value does not have to be the same as the provider may choose to change what the consumer sends them to a more appropriate value.

**Comment by lucywilcock** [comment]
This has been completed and is in the develop branch.

The provider is now forced to send back a preferred branch. Two tests now exist to check this. One where the consumer sent a preferred branch and one where they did not.
