### ISSUE TITLE
The 1.1.0 release contains the 1.1.1 changes

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#39]
The 1.1.1 changes got merged into the 1.1.0 version of the test suite when it was in master, we need to branch a 1.1.0 release branch and pick out the 1.1.1 changes leaving 1.1.0 fixes in place so that there is a correct 1.1.0 version of the test suite.

**Comment by lucywilcock** [comment]
I have updated the 1.1.0 release branch. 

This should be reviewed before closing.

**Comment by lucywilcock** [comment]
James has reviewed and approved.

The 1.1.0 is now tagged and a release branch exists for any future changes. Master is now 1.1.1 and develop is 1.2.0.
