### ISSUE TITLE
Register Patient telecom and address

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#40]
The 1.1.1 specification says that the consumer can only send temp telecom and temp address details. If the consumer send them the provider should store the details.

I have updated the register patient tests so it only passes in address and telecom with use of temp but we need to add a new test that if the telecom and address elements are passed in that they are returned in the patient resource.

**Comment by lucywilcock** [comment]
Can we also test that is a address or telecom with a use other than temp is sent that the response is an error.

**Comment by damian-answ** [comment]
1. Address passed as parameter is not returned in actual demonstrator version (only mocked)
2. Same situation with telecom
(look at StaticElementsHelper class)

**Comment by damian-answ** [comment]
commited changes to  "1.1.1-TelecomAndAddress" branch (created from master)
# test accoutding to returned elements cannot pass until demosntrator will be updated (mock stuff)

**Comment by lucywilcock** [comment]
This looks fine. Commit to master and develop.

Issue 63 has been created for the demonstrator changes.
