### ISSUE TITLE
Lists Update

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#41]
There have been some updates to the spec.

- The code should now check for specific SNOMED codes (http://gpconnect.netlify.com/accessrecord_structured_development_list.html#code)
- The empty reason code has been slightly altered and the note requirements for when the list is empty has changed slightly (http://gpconnect.netlify.com/accessrecord_structured_development_list.html#emptyreason).

**Comment by saurabhkjain** [comment]
Pushed the changes for the test suite and the demonstrator to the feature/1.2.0 beta branch. 

Needs to be reviewed.

**Comment by lucywilcock** [comment]
A couple of corrections:

1. The codes on the actual allergies (in the database) do not need to be changed. These are the SNOMED codes for the actual allergies. It is the code sent through on the list itself that should be altered. (This has been done correctly on the medications list). 
2. There are two lists sent for allergies: active and resolved. The list code for differs depending on the list. The resolved code is not yet decided on. The test suite currently only tests for the active code. Can you put something in place to check for both, depending on which allergy list it is, ready for when we get the final resolved code.

**Comment by saurabhkjain** [comment]
pushed the code to develop
