### ISSUE TITLE
Update to allergies tests

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#42]
Update the following in line with the latest [spec](http://gpconnect.netlify.com/accessrecord_structured_development_allergyintolerance.html)

- The clinical status should never be set to inactive
- The OnsetDateTime is now required, not mandatory. The test can be removed.
- Recorder is now mandatory, check that it is not null.
- The reaction manifestation test should check the the specific codes being used if possible. E.g. in case of the reaction as a severity.

**Comment by damian-answ** [comment]
add clinical status should never be set to inactive
remove  TheAllergyIntoleranceOnsetDateTimeShouldBeValid
add TheAllergyIntoleranceRecorderShouldBeValid
add nullFlavor check in reaction.manifestation

test suite changes on branch: updateToAllergiesTest-#42
Demonstrator changes on branch: feature/1.2.0-beta

**Comment by lucywilcock** [comment]
Reviewed, looks fine. Manifestation tests will need updating after spec is clarified, as discussed. Merged with 1.2.0-beta branch.
