### ISSUE TITLE
Update to Bundle tests

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#43]
For the structured record requests, the [bundle](http://gpconnect.netlify.com/accessrecord_structured_development_bundle.html) requires a meta.lastUpdated field. This should be tested for in both the medications and allergies tests.

**Comment by saurabhkjain** [comment]
Pushed the code to feature/1.2.0-beta

**Comment by lucywilcock** [comment]
Looks good.
