### ISSUE TITLE
Test failing: OrganizationSearchSendingMultipleIdentifiersResultingInFailure

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#44]
The test OrganizationSearchFeature.OrganizationSearchSendingMultipleIdentifiersResultingInFailure is failing in 1.1.1 with the following error:
- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.

**Comment by damian-answ** [comment]
There are no ORG2 element in dictionary, add ORG1 identifier twice.

**Comment by lucywilcock** [comment]
Test now passes.
