### ISSUE TITLE
1.2.0 - Empty test responses

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#45]
The following tests do not return any response details in the httpContext files created.
Ie..
```
  <response>
    <responseContentType />
    <responseStatusCode>0</responseStatusCode>
    <responseTimeInMilliseconds>-1</responseTimeInMilliseconds>
    <responseTimeAcceptable>true</responseTimeAcceptable>
    <responseHeaders />
    <responseBody />
  </response>
```

- Retrieve the medication structured record section for a patient with the prescriptions parameter added incorrectly-1
- Retrieve the medication structured record section with the medicationDatePeriod part parameter but without the includeMedications parameter-1
- Retrieve the medication structured record section with the prescriptions part parameter but without the includeMedications parameter-1

**Comment by damian-answ** [comment]
mentioned tests were removed
