### ISSUE TITLE
Definition of the constrained fhir resources is not specified correctly

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#5]
The definition for the constrained fhir resources are not clear and there are contradictions in the specification sections which set out the constrained fhir resources. There needs to be better documentation and a more clear link to the documentation as it is currently quite hard to find.

The main issue is that the Resource Delta (https://nhsconnect.github.io/gpconnect/datalibrary_delta_composition_resource.html) does not match the Constrained fhir resource reference (http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-carerecord-composition-1.html). Cardinality and notes do not match for some fields, for example "author" in FHIR has a cardinality of 1..* but in hte resource delta it has the FHIR resource cardinality as 0..1 being maintained from 0..1, should this be mandatory or not.

The resource delta's need expanding to cover all fields or the contrained fhir resource spec needs to be updated to be an accurate representation of the requirements, there should only be a single source of information/truth.

It would be better to just have the standard Fhir resources and use the resource delta to say what is mandatory or optional. Some elements on the resource delta's have been given a cardinality of 0..0, which seems like a bad decision as you may want to use this in the future so it would be better to make it 0..1 or 0..* with a comment saying it is not required for GP Connect.

NOTE: I will add any specific example of this on which we need a decision in additional comments below.

**Comment by james-answer** [comment]
For the constrained Patient resource, should the name fields be mandatory, if so which ones.

http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-patient-1.html

The above link implies that the "use" for name is required but should the "family", "given" and "prefix" also be mandatory? Should the text version of the name be mandatory?

The specifcation needs to be updating and the test to match. We are assuming that the "family", "given" are mandatory as they are required for a PDS trace.

**Comment by james-answer** [comment]
For Patient Telecom which is optional, if it is included then the "system" and "value" are mandatory accoring to the following.

http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-patient-1.html

It also implies that the "use" element should also be mandatory as it has "Binding Strength - Required" in the Description section. Does this mean that the "use" should also be mandatory or does it actuall have a cardinality of 0..1?

**Comment by james-answer** [comment]
For the constrained patient resource, the "gender" has a cardinality of 0..1 but in the description the "Binding Strength" is "Required" so should this be mandatory rather than optional?

**Comment by InteropAdmin** [comment]
The cardinality of "0..1" means that that element is optional. However if it is populated the code is "required" to be from the stated value set.

**Comment by james-answer** [comment]
In the patient constrained fhir resource what address content should be mandatory. Currently having an address included is not mandatory for a patient but when an address is included the spec, as per the link below, no elements are mandatory according to the cardinality but the description shows the "use" and "type" elements to be required as per the binding strength.

http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-patient-1.html

Should the "use" and "type" have a cardinality or 1..1 and should there be a mandatory address included, either in the "text" field or in the seperate fields, i.e. postalCode, line, district, etc. If seperate fields, which ones are really mandatory, postalCode and line or more?
