### ISSUE TITLE
Amend Appointment test checking for incorrect error

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#66]
The test "Amend appointment and update element which cannot be updated" is checking for the incorrect error code and message.

The test is looking for "Bad Request" but in the spec:

https://developer.nhs.uk/apis/gpconnect-1-1-1/appointments_use_case_amend_an_appointment.html#error-handling

The error code should be 422 and "INVALID_RESOURCE"

**Comment by saurabhkjain** [comment]
Updated the demonstrator and acceptance test code to match the spec.

**Comment by james-answer** [comment]
Changes look good and is already in master so will close the github issue.
