### ISSUE TITLE
V1.2.0 - Structured Request Change

### ISSUE THREAD

**Issue by lucywilcock** [nhsconnect/gpconnect-provider-testing#68]
The structured record request has been changed. This will require the demonstrator and test suite to be updated to the latest format. See below for the new structured request.

![image](https://user-images.githubusercontent.com/36481827/42505177-e56e0dc8-8435-11e8-86b0-778af2571b71.png)

**Comment by lucywilcock** [comment]
On hold while this is review. Changes are in structured-request-change branch.

**Comment by james-answer** [comment]
This change has been reverted due to lack of compliance to the fhir specification and difficulty with profiling the request in the STU3 method of profiling request parameters.
