### ISSUE TITLE
Logical ID check Appointments and Structured

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-provider-testing#69]
Add a validation step to Appointments and structured to check that all resources have a logical ID. This was identified as missing in the current test suite.

**Comment by saurabhkjain** [comment]
Pushed the changes to develop

**Comment by james-answer** [comment]
I have moved the changes to a feature branch as I needed to test the structured tests so that I could merge them to master, in order to do a 1.2.0-rc release of the tests suite.

**Comment by james-answer** [comment]
There are a couple of issues which need fixing:

1. For test scenario "Retrieve the allergy structured record section for a patient including resolved allergies" the "When" step has now gotten a load of spaces in the operation ("GpcGetStructuredR	ecord") which means that the test will not run as there will be no step definition which matches that step.

2. It would probably be worth adding the check for logical id on "AllergyIntolerance" resource also to the first test scenario which includes resolved allergies as the include might change the way the resources are populated.

3. In the first allergy test scenarios, where all resources are returned, we should check that if any of the key actor or supplimentary resources (Practitioner, Organization and Practitioner Role) are included that they also include a logical id.

4. In the medication feature file, in the first test where all resources should be returned, we should check that all the medication related resources have logical ids, "MedicationStatement", "MedicationRequest" and "Medication", currently the MedicationStatement and MedicationRequest are not checked for logical ID.

5. In the medication feature file, in the first test where all resources should be returned, we should check that if any of the key actor or supplimentary resources (Practitioner, Organization and Practitioner Role) are included that they also include a logical id.

**Comment by saurabhkjain** [comment]
Pushed code to feature/Logical_ID branch.
