### ISSUE TITLE
Add extra tests to cater for the filter combinations that could be submitted as part of a SearchforSlots request 

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#71]
New search filter parameters have been added to in release 1.2.1 to enable a consumer to search for free slots using a combination of no search filter,  with organisation type set only,  with organisation code set only and with organisation type set and organisation code set, see:

https://nhsconnect.github.io/gpconnect/appointments_slotavailabilitymanagement.html#appointment-availability-control

These scenarios need applying to the test suite.

**This change has already been applied to the forthcoming 1.2.1 release of the test suite so logging for information**

**Comment by rbutterf** [comment]
Added tests for all combinations of search filter requests
