### ISSUE TITLE
Remove the check from the test suite which validates that last update is present in the meta data element

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#72]
Task to remove the check from the test suite which validates that last update is present in the meta data element from all resources and to add specific tests that check that the lastUpdated element is not returned for Structured resources.

**This change has already been applied to the forthcoming 1.2.1 release of the test suite so logging for information**

**Comment by rbutterf** [comment]
Removed test for LastUpdated for all resources and added specific tests for Structured Resources
