### ISSUE TITLE
Structured clinical resources - negative tests for 'Do Not Use' elements

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#73]
Add tests to check that for Structured resources only, that the elements marked in the 'Do Not Use' sections for each resource are not present - if they are then an error will be returned

**This change has already been applied to the forthcoming 1.2.1 release of the test suite so logging for information only**

**Comment by rbutterf** [comment]
Added tests for Medications, MedicationStatement, MedicationRequests, List, Bundle, AllergyIntolerance
