### ISSUE TITLE
DeliveryChannel-2 extension - check to see present on the Appointment and Slot resources

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#75]
Raised to ensure that there are tests to ensure that the deliveryChannel-2 extension is present in the Appointment and Slot resources 

**This change has already been applied to the forthcoming 1.2.1 release of the test suite so logging for information only**

**Comment by rbutterf** [comment]
Added following tests to use deliveryChannel-2 
Scenario Outline: Book single appointment for patient with Extensions
Scenario Outline: I perform a successful retrieve appointment with Extensions
Scenario Outline: I perform a successful Read appointment with Extensions
Scenario Outline: I perform a successful amend appointment with Extensions
Scenario Outline: I perform a successful cancel appointment with Extensions
