### ISSUE TITLE
If-Match HTTP header on Amend & Cancel appointments only

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#76]
Change to the test suite to ensure that the If-Match HTTP header tests are created for Amend Appointment & Cancel Appointment only 

Add tests that use the If-Match header with the correct ETag versionId to check that the provider supports If-Match header checking

Add tests that use the If-Match header with the incorrect ETag versionId to check that the provider supports If-Match header checking and correctly fails to apply an update where the ETag versionId is incorrect

**This change has already been applied to the forthcoming 1.2.1 release of the test suite so logging for information only**

**Comment by rbutterf** [comment]
Amend Appt 
Scenario: Amend appointment send an update with an invalid if-match header
Scenario:Amend appointment set etag and check etag is the same in the returned amended appointment

Cancel Appt
Scenario: Cancel appointment verify resource is updated when an valid ETag value is provided
Scenario: Cancel appointment verify resource is not updated when an out of date ETag value is provided
