### ISSUE TITLE
Book Appointment - Delivery Channel and Practitioner role on the appt resource

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#78]
Add test to book appointment for inclusion of the delivery channel and practitioner role on the appointment resource. 
The elements are optional so we need additional tests with and without the extensions so that we know the provider accepts both with and without these new extensions.

**Comment by rbutterf** [comment]
Added test to Book appointment 
Scenario Outline: Book single appointment for patient with optional elements
with | OrgType | DeliveryChannel | PracRole |
