### ISSUE TITLE
Error codes - clarification on what should be returned when part of the identifier element is removed

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#81]
The following two tests in the test pack are expected to fail on the following:

“Book Appointment and remove identifier value from the appointment booking” expects “INVALID_RESOURCE” and HTTP code 422.
“Register patient containing identifier without mandatory system elements” expects “BAD_REQUEST” and HTTP code 400.
 
The difference is the book appointment test provides no identifier.value, and the register patient test provides no identifier.system. Is there are reason for the different error codes?

Please can you advise to confirm as there appears to be a lack of consistency in what is expected to be returned

**Comment by rbutterf** [comment]
so no changes to the test suite are required

**Comment by AndrewGuiseley** [comment]
Agreed - l have updated a few manual tests to check for the optional diagnostic element - Closed
