### ISSUE TITLE
Possible change to the invalid cache tests

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#82]
At the moment the 'invalid response check caching headers exist' tests check that the following is returned '"no-store", "The response payload should contain a resource."

One of the Providers returns 'no-store, must-revalidate, no-cache, max-age=0' - as the requirement is to only return 'no-store' (see https://nhsconnect.github.io/gpconnect/development_general_api_guidance.html#managing-return-content) would it be possible to change the test to pass if only 'no-store' is returned anywhere in the response?

**Comment by rbutterf** [comment]
amended test suite to check if contains "no-store" (not equals "no-store").. demonstrator needs to be changed to test fully.

**Comment by SimonFarrowNHS** [comment]
Does not seem to affect the demonstrator

**Comment by AndrewGuiseley** [comment]
Re-tested against the Provider endpoint - caching tests now pass as expected - closed
