### ISSUE TITLE
Structured test suite - Medication List Title

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#84]
Test 'CheckWarningCodeIsPopulatedForAPatient'

On investigation, it appears the test is expecting “Medication List” in the list Title and we are providing "Medications and medical devices".

According to this page https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured_development_list.html, Title should be populated as follows:
title
Data type: String	Optionality: Mandatory	Cardinality: 1..1
Descriptive name for the list. This will be taken from the ‘display’ element from the ‘code’ field.

Our understanding is that this is “Medications and medical devices”, as we have provided.

**Russell - can you confirm that the fix is included in the 1.2.1 version of the test suite?**

**Comment by rbutterf** [comment]
demonstrator changed .. tested OK so can close
