### ISSUE TITLE
Structured test suite - Missing ValueSet in test pack

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#86]
Clarification as to whether and if so why the ValueSet-CareConnect-ListWarningCode-1.xml is missing from the test suite.

Extract from the Provider - 'We believe this was because, as https://fhir.nhs.uk was down for some of this morning, the test pack had access only to the local list of the Value Sets

**Comment by rbutterf** [comment]
Added valueset to directory FHIR/NHS/ValueSets for Provider testing release 1.2.1 ...needs adding to GitHub repoistory
