### ISSUE TITLE
Structured test suite - List emptyReason and associated Note field

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#87]
In AccessStructuredMedicationSteps.cs, in the method TheListOfMedicationStatementsShouldBeValid, the test is expecting the list’s EmptyReason.Text to be set to “noContent” whereas the page https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_list.html specifies:

A FHIR code of No Content recorded SHALL be used if a query returns no results to enter into a list. In this case the ‘note’ field SHALL be populated with the text ‘Information not available’.

EMIS are populating the emptyReason Codeable Concept with the value from https://fhir.nhs.uk/STU3/ValueSet/CareConnect-ListEmptyReasonCode-1 (in the same way as the Warning).

**Comment by rbutterf** [comment]
Amended Test Suite for List resource validation (Empty List)
Note = "Information not available"
EmptyReason.Code = "no-content-recorded"
EmptyReason.Display = "No content recorded"

Demonstrator needs changing
