### ISSUE TITLE
Structured test suite - Associated List Note element

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#88]
Clarification of what should be in the lists Note element. The expectation of the test is that the List's note field must be populated if the list is empty.’ in the list’s Note field, which does not match the contents highlighted what is listed at:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_list.html 

Does the Note field have to be populated and, if so, what should it contain? This applies to several tests

Assigned to Jonny initially as we need clarification on what should be populated in the Lists Note element

**Comment by jonnyry** [comment]
Sorry I'm not the author of this part of the spec - reassigned to Pete.

**Comment by rbutterf** [comment]
Test suite amended to
List.Note = "Information not available"

**Comment by Fitz1006** [comment]
Hi Pete - Test - confirm receipt

**Comment by PeteSalis** [comment]
This looks like it was sorted by Russell a while ago. his update above is correct. From the spec on the list page for the element emptyReason

'A FHIR code of No Content recorded SHALL be used if a query returns no results to enter into a list. In this case the ‘note’ field SHALL be populated with the text ‘Information not available’,'
