### ISSUE TITLE
Structured test suite - ‘Resolved allergies’ vs ‘Ended allergies (record artifact)’

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#89]
CheckAllergyLegacyEndReason (among others) expects the List coding display for resolved allergies to be ‘Resolved Allergies’, whereas the Provider system is providing ‘Ended allergies (record artifact)’. 

According to the definition here: https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_list.html, it should be ‘Ended allergies (record artifact)’.

**Comment by rbutterf** [comment]
Amended Test Suite to check for  ‘Ended allergies (record artifact)’
demonstrator needs changing
