### ISSUE TITLE
Structured test suite - ‘the lists are valid for a patient without allergies’ 

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#90]
CheckAllergyWarningCodeIsPopulatedForAPatient includes a method within AccessStructuredAllergySteps.cs called TheListsAreValidForAPatientWithooutAllergies (sic).

Within this test is the line ‘list.EmptyReason.ShouldBeNull()’. However, the Provider response has populated the EmptyReason field in the list, which they believe makes sense, as the list is empty because the patient has no allergies (as the test method name suggests).

I assume the list empty reason should be populated for a patient without allergies. Assigned to Jonny to confirm.

**Comment by PeteSalis** [comment]
The emptyList reason should be populated if no allergies are recorded and it has not been specifically recorded that the patient has 'No known allergies'. From the allergies guidance page in the spec,

'Where there are no allergy or intolerance entries in the patient record, but no explicit recording of the ‘No Known Allergies’ concept and equivalents, then systems MUST return an empty List with an emptyReason FHIR code: “No content recorded” and a List.note with the text:

Information not available.'
