### ISSUE TITLE
Structured test suite - Patient that has opted out of data sharing

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#91]
Taken directly from the Provider query:

According to https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html, if a request is made for data on a patient who has requested their record not be shared, the response should be “403 forbidden”, which is what our code is doing; however, the test RetrieveTheAllergyStructuredRecordSectionForAPatientExcludingResolvedAllergies for Patient15 expects a status code of “OK”.

Assigned to Jonny to confirm the correct behaviour

**Comment by jonnyry** [comment]
The following error should be returned - (403 NO_PATIENT_CONSENT)

https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html#example-no-patient-consent-to-share

This is in line with HTML.

**Comment by rbutterf** [comment]
patient15 has now been removed form the Allergies tests
