### ISSUE TITLE
Structured test suite - Clarification on 'CheckAllergyWarningCodeIsPopulatedForAPatient' test 

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#92]
Taken directly from the Provider query:

According to the Test Suite Prerequisites, Patient14 is not on spine but is on the provider.

The test CheckAllergyWarningCodeIsPopulatedForAPatient uses Patient14 yet expects the response code to indicate success.

**Comment by rbutterf** [comment]
Patient14 should be on Spine... Pre-requisites changed to Patient17 not to be on Spine

**Comment by rbutterf** [comment]
after discussions have changed the pre-req's to use patient17 for excluded allergies and left patient14 as not on spine.

amended test CheckAllergyWarningCodeIsPopulatedForAPatient to use patient17
