### ISSUE TITLE
Structured test suite - EmptyReason.Coding query

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#93]
Taken directly from the Provider query:

The test RetrieveTheAllergyStructuredRecordSectionExcludingResolvedAllergiesForAPatientWithoutAnyAllergies expects the  list.EmptyReason.Coding details to be as follows: System http://hl7.org/fhir/special-values, Code “nocontentrecorded” and Display “No content recorded”; our response has the following: System https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-ListEmptyReasonCode-1, Code “no-content-recorded” and Display “No Content Recorded”.

We believe ours matches the specification: https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-List-1.

Believe the system, code and display elements need to be amended as suggested. Assigned to Russell for investigation

**Comment by rbutterf** [comment]
amended as per GitHub ref #87
