### ISSUE TITLE
Structured test suite - GetResourceForRelativeURL query

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#94]
Taken directly from the Provider query:

The test RetrieveTheAllergyStructuredRecordSectionForAPatientExcludingResolvedAllergies (among others) calls a method named TheAllergyIntolerancePatientShouldBeValidAndResolvable in AccessStructuredAllergySteps.cs which, in turn, called a method named GetResourceForRelativeURL in HttpSteps.cs. 

This method appears to be trying to look up a patient’s NHS number but is unsuccessful, causing the test(s) to fail.

**Comment by rbutterf** [comment]
the test suite uses the patient reference id field returned in the Allergy resource to access the NHSNo.csv file which holds the NHS no that is used to do a Patient lookup..  So the Patient id field (Patient/x) needs to correspond to the correct value (ie if looking for Patient1 in the test then the reference returned should be Patient/1

**Comment by rbutterf** [comment]
No

**Comment by SimonFarrowNHS** [comment]
Feel free to expand :-)

**Comment by rbutterf** [comment]
demonstrator issue #95 is 'If-Match header support for Amend and Cancel' (Appointments not StructuredAllergies)

**Comment by SimonFarrowNHS** [comment]
Sorry I meant provider test #95

**Comment by rbutterf** [comment]
yes same as #95 but was just commenting on what the test suite does and why it uses the NHS Number .. so Andrew could respond to the Provider's email/query
