### ISSUE TITLE
Change required to the HttpRequestConfiguration.cs file

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#98]
The following change needs to be made (it is a change to add the spine proxy to the URL):

Go to the file: HttpRequestConfiguration.cs. Line 89 should look like:
 
 var baseUrl = Protocol + ((FhirServerPort != "") ? FhirServerUrl + ":" + FhirServerPort + FhirServerFhirBase : FhirServerUrl + FhirServerFhirBase);
 
Change it to:
 
 var baseUrl = **sspAddress +** Protocol + ((FhirServerPort != "") ? FhirServerUrl + ":" + FhirServerPort + FhirServerFhirBase : FhirServerUrl + FhirServerFhirBase);

**Comment by rbutterf** [comment]
amended code ... already tested in dev env against SSP/TPP
