### ISSUE TITLE
Foundations and Appointments - confirmation of validity of error codes returned

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#99]
Between the DeliveryChannel branch and the 1.2.1 release of the test suite, the “Amend appointment and send an invalid appointment resource” and “Amend appointment invalid response check caching headers exist“ tests have changed from expecting 422/INVALID_RESOURCE to now expect 400/BAD_REQUEST.

Ticket raised to investigate the above and confirm what should be the correct error returned for the above scenarios

**Comment by rbutterf** [comment]
reverted tests to DeliveryChannelBranch (1.2.0) branch and tested OK
